e-commerce/website/models.py
from website import create_app
from flask_login import UserMixin
from . import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    nom = db.Column(db.String(150))
    prenom = db.Column(db.String(150))
    email = db.Column(db.String(200), unique = True)
    password = db.Column(db.String(100))

e-commerce/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()

db_name = "e-commerce.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'cdslkfhefhcdsjlcbsk'
    app.config['SQLALCHEMY_DATABASE_URI']= f'sqlite:///{db_name}'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix = "/")
    app.register_blueprint(auth, url_prefix="/")
    
    from .models import User

    with app.app_context():
        db.create_all()
  
  
    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))


    return app

def create_database(app):
    if not path.exists('website/' + db_name):
        db.create_all(app=app)
        print('Base de données créée!')

e-commerce/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for 
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db 
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)

@auth.route('/login', methods =['GET','POST'])

def login():
    login_user
    if request.method == 'POST' and 'email' in request.form and 'password' in request.form:
        email1 = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email1).first()
        if user:
            if check_password_hash(user.password, password):
                #flash('Connexion Réussie!', category='success')
                login_user(user)
                return redirect(url_for('views.home'))
            else:
                flash('Mot de passe incorrect', category='error')
        else:
            flash('Please enter correct email !', category='error')
    return render_template('login.html', user=current_user)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/register', methods = ['GET','POST'])
def register():
    if request.method == 'POST' and 'nom' in request.form and 'prenom' in request.form and 'email' in request.form :
        userName = request.form.get('nom')
        userPname = request.form.get('prenom')
        password = request.form.get('password')
        email1 = request.form.get('email')
        account = User.query.filter_by(email=email1).first()
        if account:
            flash('Account already exists !', category='error')
        elif not userName or not userPname or not password or not email1: 
            flash('Veuillez remplir tous les champs', category='error') 
        else:
            new_user = User(email=email1, nom=userName, prenom=userPname, password=generate_password_hash(password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Compte créé avec succès', category='success')
            return redirect(url_for('auth.login'))
    elif request.method == 'POST':
        flash('Please fill out the form', category='error')
    return render_template('register.html', user = current_user)

e-commerce/website/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

views = Blueprint('views',__name__)


@views.route("/home")
@login_required
def home():
    return render_template("home.html", user = current_user)

@views.route("/")
def accueil():
    return render_template("acceuil.html")

e-commerce/website/templates/acceuil.html
<html>
  <head>
    <title>Acceuil</title>
    <link rel="stylesheet" href="/static/css/acceuil.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/acceuil.css')}}">
    <style>
        footer {
            background-color: #333;
            color: #fff;
            padding: 50px 0;
        }
          
        footer h3 {
            color: #fff;
            font-size: 18px;
            margin-bottom: 30px;
            text-transform: uppercase;
        }
          
        footer p, footer ul, footer li {
            font-size: 14px;
            color: #999;
            margin-bottom: 20px;
        }
        
        footer a {
            color: #999;
        }
          
        footer a:hover {
            color: #fff;
        }
          
        footer .list-inline-item i {
            font-size: 24px;
            margin-right: 10px;
        }
          
        footer .copyright {
            font-size: 14px;
            color: #999;
            text-align: center;
            padding-top: 20px;
        }
    </style>
  </head>
  <body>
    <div class="navbar">
      <div>
        <a href="#">
            <img src="/static/image/salamandre2.png" alt="Lizard Logo">
            </a>
            <div class="navbar-title">SALAMANDER</div>
      </div>
      <div>
      <a href="{{url_for('auth.login')}}">Se connecter</a>
      <a href="{{url_for('auth.register')}}">S'inscrire</a>
    </div>
    </div>

    
    <div class="content">
      <h2>Bienvenue sur la SALAMANDER STORE</h2>
      <p>Les chiens sont souvent considérés comme les meilleurs amis de l'homme et pour une bonne raison. 
        Ils sont fidèles, affectueux, protecteurs et amusants. Les chiens peuvent également offrir un soutien incroyable en tant que compagnons pour les personnes souffrant de dépression, d'anxiété et de solitude. 
        De plus, certains chiens sont formés pour aider les personnes ayant des besoins spéciaux, tels que les personnes aveugles ou sourdes.
        En général, les chiens sont des animaux incroyables qui apportent une richesse incroyable à la vie de leurs propriétaires. 
        C'est pourquoi il est si important de les traiter avec amour et respect, et de s'assurer qu'ils reçoivent les soins nécessaires pour vivre heureux et en bonne santé.</p>
        <p>
            Nous croyons que les chiens sont les compagnons les plus merveilleux que l'on puisse avoir, et nous sommes fiers de les proposer à nos clients.
            Nos chiens sont soigneusement sélectionnés pour leur tempérament doux et leur santé robuste, et nous sommes certains que vous tomberez amoureux de l'un d'entre eux à première vue.
            Si vous êtes à la recherche d'un nouveau compagnon à fourrure, nous invitons à visiter notre sélection de chiens disponibles. 
            Nous sommes là pour répondre à toutes vos questions et pour vous aider à trouver le chien parfait pour votre famille. 
            N'hésitez pas à nous contacter pour en savoir plus sur nos chiens et pour organiser une rencontre avec l'un d'entre eux.<br/>
            Nous sommes convaincus que nos chiens apporteront joie et amour à votre vie, et nous sommes impatients de vous les présenter.
        </p>
    </div>
    <div class="container">
        <img src="/static/image/chien3.jpg" alt="Chien 3" class="chien-img">
        <img src="/static/image/chien4.jpg" alt="Chien 4" class="chien-img">
    </div>
    <div>
        <p>Pour avoir accès à la collection entière veuiller vous <a href="{{url_for('auth.login')}}">connecter</a>  si vous aviez déjà un compte au cas contraire veuillez vous <a href="{{url_for('auth.register')}}">inscrire</a> </p>
    </div>
    <div>{% extends "footer.html" %}</div>
  </body>
</html>

e-commerce/website/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <title>Document</title>
</head>
<body>
    <footer>
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <h3>À propos de nous</h3>
              <p>Nous sommes une entreprise passionnée par les chiens et nous offrons une variété de races de chiens de qualité pour les familles et les amoureux des animaux.</p>
            </div>
            <div class="col-md-4">
                <h3>Contact</h3>
                <ul>
                  <li>Email: contact@ventedechiens.com</li>
                  <li>Téléphone: +33 123 456 789</li>
                  <li>Adresse: 123 Rue de la Chienne, 75000 Paris, France</li>
                </ul>
              </div>
              <div class="col-md-4">
                <h3>Suivez-nous</h3>
                <ul class="list-inline">
                  <li class="list-inline-item">
                    <a href="#">
                      <i class="fab fa-facebook-f"></i>
                    </a>
                  </li>
                  <li class="list-inline-item">
                    <a href="#">
                      <i class="fab fa-twitter"></i>
                    </a>
                  </li>
                  <li class="list-inline-item">
                    <a href="#">
                      <i class="fab fa-instagram"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <p class="text-center">&copy; Copyright 2023 VentedeChiens. Tous droits réservés.</p>
              </div>
            </div>
          </div>
        </footer> 
</body>
</html>

      

e-commerce/website/templates/home.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="/static/css/home.css">
  <link rel="stylesheet" href="/static/css/bootstrap.css">
  <link rel="stylesheet" href="{{url_for('static', filename='css/home.css')}}">
</head>
<body>
  <div class="navbar">
    <div>
      <a href="#">
      <img src="/static/image/salamandre2.png" alt="Lizard Logo">
      </a>
      <div class="navbar-title">SALAMANDER</div>
    </div>
    <div>
      <a href="{{url_for('auth.logout')}}">Logout</a>
    </div>
  </div>
  <div class="container"><h2>Dogs Images</h2></div>
  <div class="container">
    <img src="/static/image/chien1.jpg" alt="Chien 1" class="chien-img">
    <img src="/static/image/chien2.jpg" alt="Chien 2" class="chien-img">
    <img src="/static/image/chien3.jpg" alt="Chien 3" class="chien-img">
    <img src="/static/image/chien4.jpg" alt="Chien 4" class="chien-img">
    <img src="/static/image/chien5.jpg" alt="Chien 5" class="chien-img">
    <img src="/static/image/chien6.jpg" alt="Chien 6" class="chien-img">
    <img src="/static/image/chien7.jpg" alt="Chien 7" class="chien-img">
    <img src="/static/image/chien8.jpg" alt="Chien 8" class="chien-img">
  </div>
  <div>{% extends "footer.html" %}</div>
</body>
</html>

e-commerce/website/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}Home{% endblock%}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style1.css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style1.css')}}">
</head>
<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    {% for category, message in messages %}

    {% if category =='error' %}
        <div class="alert alert-danger alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
         <span aria-hidden="true">&times;</span>
        </button>
        </div>

    {% else %}
        <div class="alert alert-success alert-dismissable fade show" role="alert">
         {{ message }}
         <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
        </button>
        </div>

    {% endif %}
    {% endfor %}
{% endif %}
{% endwith %}

<div class="container">
    {% block content %}
    {% endblock %}
</div>



</body>
</html>

e-commerce/website/templates/login.html
{% extends "index.html" %} {% block title%}Login{% endblock%}
 
{% block content %}
        <h2>User Login</h2>
        <form action="" method="post">
            {% if message is defined and message %}
                <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
            <div class="form-group">
                <label for="email">Email</label>
                <input type="text" class="form-control" id="email" name="email" placeholder="Entrer l'adresse email" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Entrer le mot de passe" name="password" required>
            </div><br>
            <button type="submit" class="btn btn-primary">S'enregistrer</button>
            <p class="bottom">Don't have an account? <a href="{{url_for('auth.register')}}"> Register here </a></p>

        </form>
        {% endblock %}

e-commerce/website/templates/register.html
{% extends "index.html" %} {% block title%}Register{% endblock%}
 
{% block content %}

        <h2>User Registration</h2>
        <form action="" method="post">
            {% if message is defined and message %}
                <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
            <div class="form-group">
                <label for="nom">Nom</label>
                <input type="text" class="form-control" id="name" name="nom" placeholder="Entrer le nom" required>
            </div>
            <div class="form-group">
                <label for="prenom">Prenom</label>
                <input type="text" class="form-control" id="pname" name="prenom" placeholder="Entrer le prenom" required>
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Entrer l'adresse email" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Entrer le mot de passe" name="password" required>
            </div><br>
            <button type="submit" class="btn btn-primary">S'enregistrer</button>
            <p class="bottom">Already have an account? <a href="{{url_for('auth.login')}}"> Login here</a></p>
        </form>
{% endblock %}